### PR TITLE
new layout - easier to manage

### LINKED ISSUE #332: use ipython layout similar to XPCS and others
There is a new recommendation to layout the `~/.ipython` directory (see [3-ID](https://github.com/APS-3ID-IXN/ipython-s3blue/issues/8) and [8-ID-I XPCS](https://github.com/aps-8id-dys/ipython-8idiuser/issues/148)).  This should be easier to understand and maintain.

### PR DESCRIPTION
**Pull request by prjemian**
There is a new recommendation to layout the `~/.ipython` directory (see [3-ID](https://github.com/APS-3ID-IXN/ipython-s3blue/issues/8) and [8-ID-I XPCS](https://github.com/aps-8id-dys/ipython-8idiuser/issues/148)).  this should be easier to understand and maintain.

fixes #332

### CODE REVIEW

**Comment by prjemian** [comment]
Now this is clear.  There are circular imports in `instruments.plans`:

* `.scans` imports `.command_list`
* `.command_list` imports `.scans`

<details>
<summary>details</summary>
<p>

```
usaxs@usaxscontrol ~/.ipython $ blueskyUSAXS
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: bluesky
Activating auto-logging. Current session state plus future input saved.
Filename       : /home/beams11/USAXS/.ipython/.logs/ipython_console.log
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
I Tue-08:48:42 - ############################################################ startup
I Tue-08:48:42 - logging started
I Tue-08:48:42 - logging level = 10
I Tue-08:48:42 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/collection.py
I Tue-08:48:42 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/mpl/console.py
I Tue-08:48:42 - bluesky framework
I Tue-08:48:42 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/check_python.py
I Tue-08:48:42 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/initialize.py
Loading metadata history from /home/beams/USAXS/.config/bluesky/bluesky_history.db
I Tue-08:48:44 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/user_dir.py
I Tue-08:48:44 - User code directory: /home/beams11/USAXS/.ipython/bluesky_plans
I Tue-08:48:44 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/metadata.py
I Tue-08:48:45 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/callbacks.py
I Tue-08:48:45 - writing to SPEC file: /home/beams11/USAXS/.ipython/20200225-084845.dat
I Tue-08:48:45 -    >>>>   Using default SPEC file name   <<<<
I Tue-08:48:45 -    file will be created when bluesky ends its next scan
I Tue-08:48:45 -    to change SPEC file, use command:   newSpecFile('title')
I Tue-08:48:45 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/aps_source.py
I Tue-08:48:45 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/permit.py
I Tue-08:48:45 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/diagnostics.py
I Tue-08:48:45 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/constants.py
I Tue-08:48:45 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/general_terms.py
I Tue-08:48:45 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/amplifiers.py
I Tue-08:48:45 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/scalers.py
I Tue-08:48:48 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/sample_data.py
I Tue-08:48:48 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/user_data.py
I Tue-08:48:49 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/autosave.py
I Tue-08:48:49 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/axis_tuning.py
I Tue-08:48:49 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/miscellaneous.py
I Tue-08:48:49 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/usaxs_motor_devices.py
I Tue-08:48:50 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/shutters.py
W Tue-08:48:50 - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
W Tue-08:48:50 - Session started when 9ID-C is not operating.
W Tue-08:48:50 - Using simulators for all shutters.
W Tue-08:48:50 - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I Tue-08:48:50 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/stages.py
I Tue-08:48:52 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/emails.py
I Tue-08:48:52 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/filters.py
I Tue-08:48:52 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/linkam.py
I Tue-08:48:52 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/monochromator.py
I Tue-08:48:52 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/protection_plc.py
I Tue-08:48:52 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/slits.py
I Tue-08:48:52 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/motors.py
I Tue-08:48:53 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/struck3820.py
I Tue-08:48:53 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/suspenders.py
I Tue-08:48:53 - Installing suspender for low APS current.
I Tue-08:48:53 - mono shutter connected = True
I Tue-08:48:53 - Defining suspend_BeamInHutch.  Install/remove in scan plans as desired.
I Tue-08:48:53 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/trajectories.py
I Tue-08:48:53 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/usaxs_fly_scan.py
I Tue-08:48:53 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/alta.py
I Tue-08:48:53 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/area_detector_common.py
W Tue-08:48:55 - Timeout connecting with Alta (9idalta:)
I Tue-08:48:55 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/blackfly.py
I Tue-08:48:55 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/pilatus.py
W Tue-08:48:56 - Timeout connecting with Pilatus 100k (usaxs_pilatus1:)
W Tue-08:48:57 - Timeout connecting with Pilatus 200kw (usaxs_pilatus2:)
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/area_detector.py
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/reporter.py
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/axis_tuning.py
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/mode_changes.py
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/filters.py
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/mono_feedback.py
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/move_instrument.py
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/a2q_q2a.py
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/plot_prune.py
I Tue-08:48:57 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/requested_stop.py
I Tue-08:48:58 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/command_list.py
I Tue-08:48:58 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/quoted_line.py
I Tue-08:48:58 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/scans.py
I Tue-08:48:58 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/cleanup_text.py
[TerminalIPythonApp] WARNING | Unknown error in handling startup files:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/IPython/core/shellapp.py in _exec_file(self, fname, shell_futures)
    338                                                  self.shell.user_ns,
    339                                                  shell_futures=shell_futures,
--> 340                                                  raise_exceptions=True)
    341         finally:
    342             sys.argv = save_argv

/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/IPython/core/interactiveshell.py in safe_execfile(self, fname, exit_ignore, raise_exceptions, shell_futures, *where)
   2710                 py3compat.execfile(
   2711                     fname, glob, loc,
-> 2712                     self.compile if shell_futures else None)
   2713             except SystemExit as status:
   2714                 # If the call was made with 0 or None exit status (sys.exit(0)

/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/IPython/utils/py3compat.py in execfile(fname, glob, loc, compiler)
    166     with open(fname, 'rb') as f:
    167         compiler = compiler or compile
--> 168         exec(compiler(f.read(), fname, 'exec'), glob, loc)
    169
    170 # Refactor print statements in doctests.

/home/beams11/USAXS/.ipython/profile_bluesky/startup/00-instrument.py in <module>
      4 """
      5
----> 6 from instrument.collection import *
      7
      8 # show_ophyd_symbols()

/home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/collection.py in <module>
     15 # from .callbacks import *
     16 from .commands import *
---> 17 from .plans import *
     18
     19 from apstools.utils import *

/home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/__init__.py in <module>
      6 from .area_detector import *
      7 from .axis_tuning import *
----> 8 from .command_list import *
      9 from .filters import *
     10 from .mode_changes import *

/home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/command_list.py in <module>
     44 from .axis_tuning import user_defined_settings
     45 from .mode_changes import mode_SAXS, mode_USAXS, mode_WAXS, mode_Radiography
---> 46 from .scans import preSWAXStune
     47 from .scans import preUSAXStune
     48 from .scans import SAXS

/home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/scans.py in <module>
     51 from .axis_tuning import tune_ar, tune_a2rp, tune_asrp
     52 from .axis_tuning import tune_mr, tune_m2rp, tune_msrp
---> 53 from .command_list import after_command_list, before_command_list
     54 from .command_list import after_plan, before_plan
     55 from .filters import insertSaxsFilters

ImportError: cannot import name 'after_command_list' from 'instrument.plans.command_list' (/home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/command_list.py)

In [1]:
```

</p>
</details>

Sort this out so there is *one* clear predecessor.

**Comment by prjemian** [comment]
Finally.  Passes the startup test at the beam line.

```
usaxs@usaxscontrol ~/.ipython $ blueskyUSAXS
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: bluesky
Activating auto-logging. Current session state plus future input saved.
Filename       : /home/beams11/USAXS/.ipython/.logs/ipython_console.log
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
I Tue-13:45:22 - ############################################################ startup
I Tue-13:45:22 - logging started
I Tue-13:45:22 - logging level = 10
I Tue-13:45:22 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/collection.py
I Tue-13:45:22 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/mpl/console.py
I Tue-13:45:22 - bluesky framework
I Tue-13:45:22 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/check_python.py
I Tue-13:45:22 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/initialize.py
Loading metadata history from /home/beams/USAXS/.config/bluesky/bluesky_history.db
I Tue-13:45:24 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/user_dir.py
I Tue-13:45:24 - User code directory: /home/beams11/USAXS/.ipython/bluesky_plans
I Tue-13:45:24 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/metadata.py
I Tue-13:45:25 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/callbacks.py
I Tue-13:45:25 - writing to SPEC file: /home/beams11/USAXS/.ipython/20200225-134525.dat
I Tue-13:45:25 -    >>>>   Using default SPEC file name   <<<<
I Tue-13:45:25 -    file will be created when bluesky ends its next scan
I Tue-13:45:25 -    to change SPEC file, use command:   newSpecFile('title')
I Tue-13:45:25 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/aps_source.py
I Tue-13:45:25 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/permit.py
I Tue-13:45:25 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/diagnostics.py
I Tue-13:45:25 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/constants.py
I Tue-13:45:25 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/general_terms.py
I Tue-13:45:25 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/amplifiers.py
I Tue-13:45:25 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/scalers.py
I Tue-13:45:28 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/sample_data.py
I Tue-13:45:28 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/user_data.py
I Tue-13:45:28 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/autosave.py
I Tue-13:45:28 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/axis_tuning.py
I Tue-13:45:28 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/miscellaneous.py
I Tue-13:45:28 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/usaxs_motor_devices.py
I Tue-13:45:30 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/shutters.py
W Tue-13:45:30 - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
W Tue-13:45:30 - Session started when 9ID-C is not operating.
W Tue-13:45:30 - Using simulators for all shutters.
W Tue-13:45:30 - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I Tue-13:45:30 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/stages.py
I Tue-13:45:32 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/emails.py
I Tue-13:45:32 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/filters.py
I Tue-13:45:32 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/linkam.py
I Tue-13:45:32 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/monochromator.py
I Tue-13:45:32 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/protection_plc.py
I Tue-13:45:32 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/slits.py
I Tue-13:45:32 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/motors.py
I Tue-13:45:33 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/struck3820.py
I Tue-13:45:33 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/suspenders.py
I Tue-13:45:33 - Installing suspender for low APS current.
I Tue-13:45:33 - mono shutter connected = True
I Tue-13:45:33 - Defining suspend_BeamInHutch.  Install/remove in scan plans as desired.
I Tue-13:45:33 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/trajectories.py
I Tue-13:45:33 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/usaxs_fly_scan.py
I Tue-13:45:33 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/alta.py
I Tue-13:45:33 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/area_detector_common.py
W Tue-13:45:35 - Timeout connecting with Alta (9idalta:)
I Tue-13:45:35 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/blackfly.py
I Tue-13:45:35 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/pilatus.py
W Tue-13:45:36 - Timeout connecting with Pilatus 100k (usaxs_pilatus1:)
W Tue-13:45:37 - Timeout connecting with Pilatus 200kw (usaxs_pilatus2:)
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/area_detector.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/reporter.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/axis_tuning.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/mode_changes.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/filters.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/mono_feedback.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/move_instrument.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/a2q_q2a.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/plot_prune.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/requested_stop.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/command_list.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/quoted_line.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/resets.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/sample_transmission.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/scans.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/cleanup_text.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/tune_guard_slits.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/derivative.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/utils/peak_centers.py
I Tue-13:45:37 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/plans/uascan.py

In [1]:
```

**Comment by jilavsky** [comment]
That looks refreshing. We now have logical structure of our packages. How do you control order of loading of these packages? Is there some include file which has this order? 
Approved, but expect I need explanation ;-)

**Comment by prjemian** [comment]
I'll walk you through this.  Look in startup/00-instrument.py, it calls instrument.collection.py which controls the process.

**Comment by prjemian** [comment]
If you close without merge, that means you don't want these changes.  Let's review first, then merge.

**Comment by prjemian** [comment]
[`00-instrument.py`](https://github.com/APS-USAXS/ipython-usaxs/blob/332-new-layout/profile_bluesky/startup/00-instrument.py) loads [`collection.py`](https://github.com/APS-USAXS/ipython-usaxs/blob/332-new-layout/profile_bluesky/startup/instrument/collection.py) which loads ...

you get the picture

**Comment by prjemian** [comment]
Went over this today with @jilavsky and we agree it is a step in the right direction.

**Pull request merged**
