### PR TITLE
make tune width a settable PV

### LINKED ISSUE #232: UsaxsMotorTunable with EpicsSignal for width
As noted in https://github.com/APS-USAXS/ipython-usaxs/issues/230#issuecomment-497853589, to have the tuning width expressed as a PV will require some redesign of our UsaxsMotorTunable.

Look at `apstools.devices.AxisTunerMixin()`

### PR DESCRIPTION
**Pull request by prjemian**
fixes #232

### CODE REVIEW

**Comment by prjemian** [comment]
Nice!  The new `width` attribute works.

```
In [1]: a_stage.r.tuner.width

In [2]: type(_)
Out[2]: str

In [3]: axis_tune_range.ar
Out[3]: EpicsSignal(read_pv='9idcLAX:USAXS:tune_ar_range', name='axis_tune_range_ar', parent='axis_tune_range', value=0.002, timestamp=631152000.0, auto_monitor=True, string=False, write_pv='9idcLAX:USAXS:tune_ar_range', limits=False, put_complete=False)

In [4]: a_stage.r.tuner.width_signal = axis_tune_range.ar

In [5]: a_stage.r.tuner.width
Out[5]: 0.002

In [6]: a_stage.r.tuner.width = .5

In [7]: a_stage.r.tuner.width
Out[7]: 0.5

In [8]: a_stage.r.tuner.width = .002

In [9]: 
```

Still needs to be configured for each axis.  Also check how `.width` is used.  Is it ever set during a plan?

**Comment by prjemian** [comment]
@jilavsky Here is an example of using a property decorator in Pyhton, to connect a PV with the tune width.  https://github.com/APS-USAXS/ipython-usaxs/blob/faeb403476df5c40b97a8f5a11bfea72235ee2e9/profile_bluesky/startup/instrument/devices/axis_tuning_patches.py#L73-L93

The unconnected case should raise an Exception or at the very least a warning.  See demonstration in previous comment.

**Comment by prjemian** [comment]
revised demo:

```
In [1]: a_stage.r.tuner.width
Out[1]: 0.002

In [2]: a_stage.r.tuner.width_signal

In [3]: a_stage.r.tuner._width_default
Out[3]: 0.002

In [4]: a_stage.r.tuner.width_signal = axis_tune_range.ar

In [5]: a_stage.r.tuner.width = .5

In [6]: a_stage.r.tuner._width_default
Out[6]: 0.002

In [7]: a_stage.r.tuner.width
Out[7]: 0.5

In [8]: a_stage.r.tuner.width = 0.002
```

Backwards-compatible now!

**Comment by prjemian** [comment]
Finally, need to cover the plan usage in `devices.axis_tuning.py`.

**Comment by prjemian** [comment]
Easy to cover the plan usage.  Since the code now uses a `@property` decorator to get the PV value, no need to make the setting in the pretune hooks.  Comment out for now, remove later after confirming this really, really works.

**Review by jilavsky — APPROVED** [review]

**Pull request merged**
