### PR TITLE
add 2 new PointGrey Blackfly cameras

### LINKED ISSUE #373: Add jpg images from 9idFLY2
We have two Blackfly cameras:

9idFLY2 providing optical images of the sample while data are collected. 
9idFLY providing X-ray images (radiography). 
For 9IDFLY2:
We want to add option to stare jpg image at the time of each data collection - USAXS, SAXS, and WAXS.  There is PV which controls this:
9idcLAX:saveFLY2Image, bo, 0=No, 1=Yes.  
Uses AD, PV prefix: 9idFLY2:

Need to set path to path of each technique (reminder, per #361 it will be e.g., CWD/09_01_UserName/09_01_UserName_saxs).  Use same name as for that technique (SAXS, WAXS, USAXS) for image but use extension jpg and jpg writer (not hdf5 writer). If PV is set to 1, trigger save jpg image in the same location as Nexus file at the time of triggering USAXS/SAXS/ or WAXS data collection. 
Camera will be configured - time/parameters/focus - manually by staff during setup until we know more and can prepare some script. 
9idcLAX:saveFLY2Image PV will be available to users on GUI and provided for user control. 

We should add 9idFLY (X-ray) camera to enable BS to collect radiography images if needed. Simply, add support since both cameras are using same AD version ond iocs are very similar. We will find use for this device later. Trust me ;-)

### PR DESCRIPTION
**Pull request by prjemian**
fixes #373

### CODE REVIEW

**Comment by prjemian** [comment]
@jilavsky - ready for your review

**Comment by prjemian** [comment]
now testing the `RE(bp.count(blackfly_optical))` test

**Comment by prjemian** [comment]
test if detector is primed

```
from instrument.devices.for_apstools import AD_plugin_primed
AD_plugin_primed(blackfly_optical.jpeg1)
```

If that result is `False`, then *prime* it:

```
%mov blackfly_optical.jpeg1.enable 1
# next step is important:   SET the write mode to "Single" (0) or plugin's Capture=1 won't stay
%mov blackfly_optical.jpeg1.file_write_mode 0
%mov blackfly_optical.jpeg1.capture 1
%mov blackfly_optical.cam.acquire 1
AD_plugin_primed(blackfly_optical.jpeg1)
```

Should be `True` now.

**Comment by jilavsky** [comment]
OK, I was confused and provided imperfect info. Radiography BalckFly is 9idFLY1 - optical is 9idFLY2.
There is not any 9idFLY, somehow I confused myself with the original camera PVs. Only two devices - radiography (9idFLY1) and optical (9idFLY2). 
Sorry for the added work.

**Comment by prjemian** [comment]
This works:

```
In [22]: blackfly_optical.stage()                                                                                                           

In [23]: blackfly_optical.trigger()                                                                                                         
D Fri-15:56:41 - make_filename: /mnt/share1/USAXS_data/2020-08/test_0001.jpg
D Fri-15:56:41 - write_path: /mnt/share1/USAXS_data/2020-08/
Out[23]: ADTriggerStatus(device=blackfly_optical, done=False, success=False)

In [24]: blackfly_optical.unstage()                                                                                                         

In [26]: blackfly_optical.read()                                                                                                            
Out[26]: 
OrderedDict([('blackfly_optical_image',
              {'value': 'f19a7804-575b-486b-8ede-af76dd93865c/0',
               'timestamp': 1598648201.1719854})])
```

but the  `RE(bp.count(blackfly_optical))` test fails with : 

```
TypeError: 'MyPointGreyDetectorJPEG' object is not iterable
```

**Comment by jilavsky** [comment]
FLY1 is not running, FLY2 is running now and is available for testing.

**Comment by prjemian** [comment]
Ok, will drop `9idFly:`

**Comment by prjemian** [comment]
still working on the `bp.count` ...

**Comment by prjemian** [comment]
Still won't `bp.count()`.  That needs research.  BUT, it will image.  Got to get a better subject to image tho:

as-received:

test_0001

auto-scaled:

test_0003

**Comment by jilavsky** [comment]
Be happy you have ANY image. It needs to be mounted and that requires someone to mill holder. It was pain to position it so it sees something else than walls ;-) This is expected image, ain't going to get better until mounted. Boring images, hopefully.

**Comment by jilavsky** [comment]
Note: this thing is at this time in continuous mode. I think you can make it count, but it needs to be in single mode. I can change this through GUI. In spec I set it to single mode and then do standard Acquire, which I suspect is bp.count.

**Comment by jilavsky** [comment]
It is in single mode now. YOu can try again and see, if you need to change the code to set the mode first. But now it may do bp.count

**Comment by prjemian** [comment]
BS has a setting as well:

```
In [7]: blackfly_optical.jpeg1.stage_sigs                                                                                                   
Out[7]: 
OrderedDict([('enable', 1),
             ('auto_increment', 'Yes'),
             ('array_counter', 0),
             ('auto_save', 'Yes'),
             ('num_capture', 0),
             ('file_template', '%s%s_%4.4d.jpg'),
             ('file_write_mode', 'Stream'),
             ('capture', 1),
             ('blocking_callbacks', 'Yes'),
             ('parent.cam.array_callbacks', 1)])
```

_might just be a problem to fix..._

**Comment by jilavsky** [comment]
Those are parameters for jpeg writer, this is main camera setting. Image mode needs to be single, not continuous or multiple.

**Comment by prjemian** [comment]
blackfly_optical.jpeg1.stage_sigs["file_write_mode"] = "Single"

did not solve the problem.

I'm happy for now that we have an image file.  We'll work out the other later if it is important.  (I suspect it will be or plans might look unusual to write.)

**Comment by prjemian** [comment]
OK, I'm done with this.  If you agree with it, then merge.

**Comment by prjemian** [comment]
@jilavsky You OK with this?

**Comment by jilavsky** [comment]
I am OK with it, we'll test it later.

**Pull request merged**
