### PR TITLE
samples scanned from text file

### LINKED ISSUE #216: run a list of samples from a text file
Like #71 (and #124), read a list of samples from a text file, ad noted in #193

This is an alternative to #139 (which is to read SPEC-style usaxs.mac file)

Derive this from the `run_Excel_file()` plan.

### PR DESCRIPTION
**Pull request by prjemian**
fixes #216

### CODE REVIEW

**Comment by jilavsky** [comment]
Looks OK, see #219

**Comment by prjemian** [comment]
@jilavsky - please review again: `beforePlan()` and `postCommandsListfile2WWW()`

**Comment by jilavsky** [comment]
Looks OK to me, need to test. Want to try sometimes? Note, I have vacations tomorrow (Friday).

**Comment by prjemian** [comment]
ready to test this afternoon before merge

**Pull request merged**
