### PR TITLE
move call to getSampleTitle() closer to actual collection events

### LINKED ISSUE #487: SampleTitle Function
Need to check when is it called. Seems to me to be called too early, before potential mode change. At high heating rates mode change take too much time and then values in names do nto match reality. This is just a check and potentially move to place closer to start of exposure.

### PR DESCRIPTION
**Pull request by jilavsky**
- FIXES #487

Move getSampleTitile to better locations

### CODE REVIEW

**Comment by prjemian** [comment]
debugging remnants can be removed

**Comment by prjemian** [comment]
@jilavsky - please remove the _debugging remnants_.  Then I'll review.

**Comment by jilavsky** [comment]
Cleaned up all debug statements from WAXS code.

**Review by prjemian — APPROVED** [review]
LGTM, merge when you are ready!

**Pull request merged**
