### PR TITLE
set value of user_data.collection_in_progress as appropriate

### LINKED ISSUE #372: Set in Progress PV in autocollection
In order to prevent Igor from moving motors while instrument moves between positions, we need to set pv: 9idcLAX:dataColInProgress to 1 when starting preUSAXStune and useModeRadiography (well, the BS equivalents) and set to 0 when done. Igor checks on this PV when attempting to move motors in epics. 
This PV is already set by execution of command file. We just need to add this to execution of the other two commands.

### PR DESCRIPTION
**Pull request by prjemian**
will fix #372

### CODE REVIEW

**Comment by prjemian** [comment]
@jilavsky : See [this question](https://github.com/APS-USAXS/ipython-usaxs/issues/372#issuecomment-682852940) before considering a merge.

**Comment by jilavsky** [comment]
I believe mode radiography needs to add unset of this value at the end of procedure. See my comment in #372

**Comment by prjemian** [comment]
@jilavsky Ready for your review and *merge*.

**Comment by jilavsky** [comment]
Yes, this looks perfect.

**Pull request merged**
