### PR TITLE
add reset_USAXS plan

### LINKED ISSUE #254: need resetUSAXS plan
Implement this in bluesky from the SPEC macro

### PR DESCRIPTION
**Pull request by prjemian**
fixes #254

### CODE REVIEW

**Comment by prjemian** [comment]
Need to handle these SPEC commands:

```
    # TODO: setplot 131 (resets SPEC plotting)
    # TODO: TITLE = SPEC_STD_TITLE
    # TODO: epics_put (sprintf("9idcUSX:%s:mode",PDstring), 2) 
    # TODO: if(NOTIFY_ON_RESET) { sendNotifications("USAXS has reset","spec has encountered a problem and reset the USAXS.");} 
    # TODO: chk_beam_off 
    # TODO: rdef _cleanup3 \'\' 
```

* What is `PDstring`?
* Where is `NOTIFY_ON_RESET`?

other `TODO:` items might have no specific bluesky conversion

**Comment by prjemian** [comment]
This *MUST* be tested once TODO items are resolved.

**Comment by prjemian** [comment]
@jilavsky : [bump](https://github.com/APS-USAXS/ipython-usaxs/pull/305#issuecomment-532270589)

**Comment by jilavsky** [comment]
tested at the beamline, seems to work as intended.

**Pull request merged**
