### PR TITLE
run python file from command_list

### LINKED ISSUE #346: enhance command_list with capability to run a config file
add to the command_list support so that it can run a config file (that installs a temporary set of changes -- from a defined list of things allowed to be changed) for the duration of the command list

### PR DESCRIPTION
**Pull request by prjemian**
fixes #346

Needs testing!

### CODE REVIEW

**Review by jilavsky — APPROVED** [review]
I think I need bit more explanation, but I get most of this.

**Comment by jilavsky** [comment]
Should there be fix for the check failure above?

**Comment by prjemian** [comment]
It's complaining about `md={}`, which is a common pattern in this code.
Maybe it's time to make the transition to`md=None` and then check for it in
the coffee body if the function.  Also, the filename parameter needs to be
defined somehow. Looks as if one step had been skipped.

**Comment by prjemian** [comment]
Test this after #443 is merged.

**Comment by prjemian** [comment]
Example to turn off dynamic time in USAXS step scans, in the `usaxs.mac` file, add:

```python
run user/uascan_dynamic_time_off.py
```

**Comment by prjemian** [comment]
`%run -i user/localfile.py` has problems finding that file

<details>

```python

In [1]: newUser("test")
I Sat-09:21:02 - Change working directory is still /share1/USAXS_data/2020-11
W Sat-09:21:02 - >>> file already exists: /share1/USAXS_data/2020-11/11_28_test/11_28_test.dat <<<
I Sat-09:21:02 - SPEC file name : /share1/USAXS_data/2020-11/11_28_test/11_28_test.dat
I Sat-09:21:02 - File will be appended at end of next bluesky scan.
W Sat-09:21:02 - No unexpired ESAFs found that match user test
W Sat-09:21:03 - No unexpired proposals found that match user test
W Sat-09:21:03 - APSBSS not updated.
W Sat-09:21:03 - You should check that PVs in APSBSS contain correct information.
Out[1]: '/share1/USAXS_data/2020-11/11_28_test'

In [2]: RE(run_command_file("pyusaxs.mac"))
I Sat-09:21:22 - Command file: pyusaxs.mac
====== ======================= ===============================
line # action                  parameters                     
====== ======================= ===============================
1      CURRENT_EXPERIMENT_NAME                                
18     run_python              user/uascan_dynamic_time_off.py
====== ======================= ===============================

I Sat-09:21:22 - memory report: pmem(rss=268877824, vms=3218493440, shared=46100480, text=2506752, lib=0, data=2696712192, dirty=0)
I Sat-09:21:22 - Measuring background for: PD_USAXS
                                                                                                                                                                                                                 
I Sat-09:21:24 - PD_USAXS range=4 gain=1e12 bkg=4125.8 +/- 359.790716945282
I Sat-09:21:24 - I0_USAXS range=4 gain=1e9 bkg=274.8 +/- 0.9797958971132712
I Sat-09:21:24 - I00_USAXS range=4 gain=1e9 bkg=453.4 +/- 0.48989794855663565
                                                                                                                                                                                                                 
I Sat-09:21:25 - PD_USAXS range=3 gain=1e10 bkg=10.0 +/- 18.0
I Sat-09:21:25 - I0_USAXS range=3 gain=1e8 bkg=266.2 +/- 0.4
I Sat-09:21:25 - I00_USAXS range=3 gain=1e8 bkg=413.6 +/- 0.48989794855663565
                                                                                                                                                                                                                 
I Sat-09:21:27 - PD_USAXS range=2 gain=1e8 bkg=1.0 +/- 0.0
I Sat-09:21:27 - I0_USAXS range=2 gain=1e7 bkg=265.2 +/- 0.4
I Sat-09:21:27 - I00_USAXS range=2 gain=1e7 bkg=410.0 +/- 0.0
                                                                                                                                                                                                                 
I Sat-09:21:29 - PD_USAXS range=1 gain=1e6 bkg=1.0 +/- 0.0
I Sat-09:21:29 - I0_USAXS range=1 gain=1e6 bkg=266.0 +/- 0.0
I Sat-09:21:29 - I00_USAXS range=1 gain=1e6 bkg=409.0 +/- 0.6324555320336759
                                                                                                                                                                                                                 
I Sat-09:21:31 - PD_USAXS range=0 gain=1e4 bkg=1.0 +/- 0.0
I Sat-09:21:31 - I0_USAXS range=0 gain=1e5 bkg=266.8 +/- 0.4
I Sat-09:21:31 - I00_USAXS range=0 gain=1e5 bkg=408.8 +/- 0.4
I Sat-09:21:31 - TR diode range=0 gain=1e5 bkg=1.0 +/- 0.0
I Sat-09:21:31 - Synchronizing detector order numbers to 655
I Sat-09:21:31 - file line 1:         CURRENT_EXPERIMENT_NAME ""
I Sat-09:21:31 - no handling for line 1:         CURRENT_EXPERIMENT_NAME ""
I Sat-09:21:31 - memory report: pmem(rss=272666624, vms=4269744128, shared=46116864, text=2506752, lib=0, data=3747962880, dirty=0)
I Sat-09:21:31 - file line 18: run_python user/uascan_dynamic_time_off.py
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/IPython/core/magics/execution.py in run(self, parameter_s, runner, file_finder)
    696             fpath = arg_lst[0]
--> 697             filename = file_finder(fpath)
    698         except IndexError:

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/IPython/utils/path.py in get_py_filename(name, force_win32)
    108     else:
--> 109         raise IOError('File `%r` not found.' % name)
    110 

OSError: File `'user/uascan_dynamic_time_off.py'` not found.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-2-2affb5dcd912> in <module>
----> 1 RE(run_command_file("pyusaxs.mac"))

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    805             self._task_fut.add_done_callback(set_blocking_event)
    806 
--> 807         self._resume_task(init_func=_build_task)
    808 
    809         if self._interrupted:

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/run_engine.py in _resume_task(self, init_func)
    929                     if (exc is not None
    930                             and not isinstance(exc, _RunEnginePanic)):
--> 931                         raise exc
    932 
    933     def install_suspender(self, suspender):

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/run_engine.py in _run(self)
   1498             exit_reason = str(err)
   1499             self.log.exception("Run aborted")
-> 1500             raise err
   1501         finally:
   1502             if not exit_reason:

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/run_engine.py in _run(self)
   1363                     else:
   1364                         try:
-> 1365                             msg = self._plan_stack[-1].send(resp)
   1366                         # We have exhausted the top generator
   1367                         except StopIteration:

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1305         plan = monitor_during_wrapper(plan, self.monitors)
   1306         plan = baseline_wrapper(plan, self.baseline)
-> 1307         return (yield from plan)
   1308 
   1309 

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1160         return (yield from plan)
   1161     else:
-> 1162         return (yield from plan_mutator(plan, insert_baseline))
   1163 
   1164 

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    801     plan1 = plan_mutator(plan, insert_after_open)
    802     plan2 = plan_mutator(plan1, insert_before_close)
--> 803     return (yield from plan2)
    804 
    805 

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    859     plan1 = plan_mutator(plan, insert_after_open)
    860     plan2 = plan_mutator(plan1, insert_before_close)
--> 861     return (yield from plan2)
    862 
    863 

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.ipython/profile_bluesky/startup/instrument/plans/command_list.py in run_command_file(filename, md)
    338         md = {}
    339     commands = get_command_list(filename)
--> 340     yield from execute_command_list(filename, commands)
    341 
    342 

~/.ipython/profile_bluesky/startup/instrument/plans/command_list.py in execute_command_list(filename, commands, md)
    451         elif action in ("run_python", "run"):
    452             filename = args[0]
--> 453             yield from run_python_file(filename, md={})
    454 
    455         elif action in simple_actions:

~/.ipython/profile_bluesky/startup/instrument/plans/command_list.py in run_python_file(filename, md)
    494         md = {}
    495     logger.info("Running Python file: %s", filename)
--> 496     get_ipython().run_line_magic("run", f"-i {filename}")
    497     yield from bps.null()
    498 

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2324                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2325             with self.builtin_trap:
-> 2326                 result = fn(*args, **kwargs)
   2327             return result
   2328 

<decorator-gen-52> in run(self, parameter_s, runner, file_finder)

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/site-packages/IPython/core/magics/execution.py in run(self, parameter_s, runner, file_finder)
    706             if os.name == 'nt' and re.match(r"^'.*'$",fpath):
    707                 warn('For Windows, use double quotes to wrap a filename: %run "mypath\\myfile.py"')
--> 708             raise Exception(msg)
    709         except TypeError:
    710             if fpath in sys.meta_path:

Exception: File `'user/uascan_dynamic_time_off.py'` not found.

In [3]: get_ipython().run_line_magic("run", f"-m uascan_dynamic_time_off")
I Sat-09:22:16 - /home/beams/USAXS/.ipython/user/uascan_dynamic_time_off.py
I Sat-09:22:16 - terms.USAXS.useDynamicTime = False

```

</details>

**Comment by prjemian** [comment]
make a new `user/localfile.py` example:

```python
def myNamer(title):
    return f"{os.path.exists(title)} : {title}"


setSampleTitleFunction(myNamer)
print(getSampleTitle(__file__))
print(getSampleTitle("purple"))
```

then try it:

```python
In [5]: %run -im localfile
I Mon-17:50:30 - /home/beams/USAXS/.ipython/user/localfile.py
True : /home/beams/USAXS/.ipython/user/localfile.py
False : purple

```

**Comment by prjemian** [comment]
Modify the `localfile.py`:

```python
from instrument.utils.cleanup_text import cleanupText
from instrument.utils import getSampleTitle
from instrument.utils import setSampleTitleFunction
import os


def myNamer(title):
    return f"{os.path.exists(title)} : {title}"


setSampleTitleFunction(myNamer)
print(getSampleTitle(__file__))
print(getSampleTitle("purple"))
print(cleanupText(getSampleTitle("Merging can be performed automatically")))
```

and run it again

```python
In [7]: %run -im localfile
I Mon-17:54:14 - /home/beams/USAXS/.ipython/user/localfile.py
True : /home/beams/USAXS/.ipython/user/localfile.py
False : purple
False___Merging_can_be_performed_automatically
```

**Comment by prjemian** [comment]
Now, try the same file content in a file in the `pwd`:

```python
In [8]: !pwd
/share1/USAXS_data/test

In [9]: !ls
blackfly2  dexela  dexela_hdf5_plugin.ipynb  saxs  waxs

In [10]: !nano tester.py

In [11]: %run -im tester
I Mon-17:58:57 - /share1/USAXS_data/test/tester.py
True : /share1/USAXS_data/test/tester.py
False : purple
False___Merging_can_be_performed_automatically

```

**Comment by prjemian** [comment]
Next, need to try a command list file.

**Comment by prjemian** [comment]
Now, create a test command file:

```
In [14]: !cat pyusaxs.mac
# file: pyusaxs.mac

CURRENT_EXPERIMENT_NAME  enable new feature
run_python  localfile.py
run         user/localfile.py

In [15]: 
```

**Comment by prjemian** [comment]
Try to run that command file now:

```python
In [15]: newUser("test")
I Mon-18:12:54 - Creating user directory: /share1/USAXS_data/2021-01/01_25_test
I Mon-18:12:54 - Change working directory is still /share1/USAXS_data/test
I Mon-18:12:54 - SPEC file name : /share1/USAXS_data/2021-01/01_25_test/01_25_test.dat
I Mon-18:12:54 - File will be created at end of next bluesky scan.
W Mon-18:12:54 - No unexpired ESAFs found that match user test
W Mon-18:12:54 - No unexpired proposals found that match user test
W Mon-18:12:54 - APSBSS not updated.
W Mon-18:12:54 - You should check that PVs in APSBSS contain correct information.
Out[15]: '/share1/USAXS_data/2021-01/01_25_test'

In [16]: RE(run_command_file("pyusaxs.mac"))
I Mon-18:13:13 - Command file: pyusaxs.mac
====== ======================= ====================
line # action                  parameters          
====== ======================= ====================
3      CURRENT_EXPERIMENT_NAME enable, new, feature
4      run_python              localfile.py        
5      run                     user/localfile.py   
====== ======================= ====================

I Mon-18:13:13 - memory report: pmem(rss=279670784, vms=3239346176, shared=46682112, text=2506752, lib=0, data=2711957504, dirty=0)
---------------------------------------------------------------------------
DisconnectedError                         Traceback (most recent call last)
/share1/USAXS_data/test/tester.py in <module>

...


/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/utils/epics_pvs.py in wrapper(self, *args, **kwargs)
    198             return fcn(self, *args, **kwargs)
    199         else:
--> 200             raise DisconnectedError('{} is not connected'.format(self.name))
    201     return wrapper
    202 

DisconnectedError: diagnostics_FE_EPS_major_fault is not connected

In [17]: diagnostics.FE_EPS.major_fault.get()
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py in _get_with_timeout(self, pv, timeout, connection_timeout, as_string, form, use_monitor)

...

/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py in _get_with_timeout(self, pv, timeout, connection_timeout, as_string, form, use_monitor)
   1113             self.wait_for_connection(timeout=connection_timeout)
   1114         except TimeoutError as err:
-> 1115             raise ConnectionTimeoutError(
   1116                 f"Failed to connect to {pv.pvname} "
   1117                 f"within {connection_timeout:.2f} sec") from err

ConnectionTimeoutError: Failed to connect to EPS:09:ID:Major within 5.00 sec

In [18]: !caget EPS:09:ID:Major
Channel connect timed out: 'EPS:09:ID:Major' not found.

```

**Comment by prjemian** [comment]
For testing, we can disable that subscription.  For operations, we need the FE_EPS to be working.  Or has something changed this past shutdown?

**Comment by prjemian** [comment]
Cut back on the supplementary data and the email notices:

```python
In [1]: sd.baseline = []

In [2]: newUser("test")
I Mon-18:22:47 - Change working directory is still /share1/USAXS_data/test
W Mon-18:22:47 - >>> file already exists: /share1/USAXS_data/2021-01/01_25_test/01_25_test.dat <<<
I Mon-18:22:47 - SPEC file name : /share1/USAXS_data/2021-01/01_25_test/01_25_test.dat
I Mon-18:22:47 - File will be appended at end of next bluesky scan.
W Mon-18:22:48 - No unexpired ESAFs found that match user test
W Mon-18:22:48 - No unexpired proposals found that match user test
W Mon-18:22:48 - APSBSS not updated.
W Mon-18:22:48 - You should check that PVs in APSBSS contain correct information.
Out[2]: '/share1/USAXS_data/2021-01/01_25_test'

In [3]: emails
Out[3]: <module 'instrument.devices.emails' from '/home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/emails.py'>

In [4]: email_notices.addresses
Out[4]: ['ilavsky@aps.anl.gov', 'kuzmenko@aps.anl.gov', 'jemian@anl.gov']

In [5]: email_notices.addresses = ['jemian@anl.gov',]
```

**Comment by prjemian** [comment]
Oooh, got an infinite loop, could not ^C out, had to close the terminal window.  Not good.

**Comment by prjemian** [comment]
from the logs:

```
bash-4.2$ tail .logs/ipython_logger.log
|2021-01-25 18:26:17.955|ERROR|25464|bluesky-session|command_list|490|bluesky-run-engine| - Exception Exception during attempt 18116 of command '('run_python', ['localfile.py'], 4, 'run_python  localfile.py')''
subject: Exception during attempt 18116 of command '('run_python', ['localfile.py'], 4, 'run_python  localfile.py')''

date: 2021-01-25 18:26:17.955301
command file: /share1/USAXS_data/test/pyusaxs.mac
line number: 4
command: ('run_python', ['localfile.py'], 4, 'run_python  localfile.py')
raw command: run_python  localfile.py
attempt: 18116
exception: File `'localfile.py'` not found.
```

**Comment by prjemian** [comment]
The `run_python_file()` function needs to walk through `sys.path` to find the first path with the `filename` provided.

**Comment by prjemian** [comment]
Still, the `run` command will not work properly because the python file being run is not inside a function so the `yield from ` code cannot be at the global level in the run file.

### command file: `pyusaxs.mac`

```python
# file: pyusaxs.mac

CURRENT_EXPERIMENT_NAME  enable new feature
run_python  localfile.py
run         user/localfile.py
run tester.py
```

### run file: `tester.py`

```python
from instrument.session_logs import logger

logger.info(__file__)

from bluesky import plans as bp
from instrument.devices import scaler0
from instrument.framework import RE
from instrument.utils.cleanup_text import cleanupText
from instrument.utils import getSampleTitle
from instrument.utils import setSampleTitleFunction
import os

def myNamer(title):
    return f"{os.path.exists(title)} : {title}"

setSampleTitleFunction(myNamer)
logger.info(getSampleTitle(__file__))
logger.info(cleanupText(getSampleTitle("Counting scaler0")))
yield from bp.count([scaler0], md=dict(purpose="testing"))
logger.info("test file complete")
```

### console output

```python
W Mon-21:44:07 - !!! tune failed for axis a_stage_r2p !!!
I Mon-21:44:08 - USAXS count time: {terms.USAXS.usaxs_time.get()} second(s)
I Mon-21:44:08 - Synchronizing detector order numbers to 2
I Mon-21:44:08 - file line 3: CURRENT_EXPERIMENT_NAME  enable new feature
I Mon-21:44:08 - no handling for line 3: CURRENT_EXPERIMENT_NAME  enable new feature
I Mon-21:44:08 - memory report: pmem(rss=329056256, vms=4618555392, shared=59478016, text=2506752, lib=0, data=3993272320, dirty=0)
I Mon-21:44:08 - file line 4: run_python  localfile.py
I Mon-21:44:08 - Running Python file: /home/beams/USAXS/.ipython/user/localfile.py
True : /home/beams/USAXS/.ipython/user/localfile.pycalfile.py
False : purple
False___Merging_can_be_performed_automatically
I Mon-21:44:08 - memory report: pmem(rss=329154560, vms=4618555392, shared=59478016, text=2506752, lib=0, data=3993272320, dirty=0)
I Mon-21:44:08 - file line 5: run         user/localfile.py
I Mon-21:44:08 - Running Python file: /home/beams/USAXS/.ipython/user/localfile.py
I Mon-21:44:08 - /home/beams/USAXS/.ipython/user/localfile.py
True : /home/beams/USAXS/.ipython/user/localfile.py
False : purple
False___Merging_can_be_performed_automatically
I Mon-21:44:08 - memory report: pmem(rss=329154560, vms=4618555392, shared=59478016, text=2506752, lib=0, data=3993272320, dirty=0)
I Mon-21:44:08 - file line 6: run tester.py
I Mon-21:44:08 - Running Python file: tester.py
  File "/share1/USAXS_data/test/tester.py", line 22
    yield from bp.count([scaler0], md=dict(purpose="testing"))
    ^
SyntaxError: 'yield' outside function

I Mon-21:44:08 - memory report: pmem(rss=329175040, vms=4618555392, shared=59482112, text=2506752, lib=0, data=3993272320, dirty=0)
I Mon-21:44:08 - memory report: pmem(rss=329162752, vms=4635340800, shared=59482112, text=2506752, lib=0, data=4010057728, dirty=0)
Out[13]: 
('a8584fcd-92ae-4748-9d55-e92bb95f0611',
 'e37518ca-d478-43e0-911d-7abe2f392b2b',
 'de729f53-caec-452a-a5ae-8bd1d36bdb47',
 '6107dcc2-ec60-472d-85f2-61399d4be8a1')

```

**Comment by prjemian** [comment]
OK, so far, we can run a python file so this can be used to make configuration settings..  But it cannot (yet) run any bluesky plans.  That means the code the file contains should execute quickly and not block execution of the RunEngine.

**Comment by prjemian** [comment]
FYI, command log file:

```python
In [23]: !cat .logs/ipython_console.log
# IPython log file

# Mon, 25 Jan 2021 21:31:48
sd.baseline = []
# Mon, 25 Jan 2021 21:31:52
email_notices.addresses = ['jemian@anl.gov',]
# Mon, 25 Jan 2021 21:31:56
newUser("test")
#[Out]# '/share1/USAXS_data/2021-01/01_25_test'
# Mon, 25 Jan 2021 21:32:02
RE(run_command_file("pyusaxs.mac"))
#[Out]# ('f5742c31-6d1a-4a58-a484-c2fe2e89c174',
#[Out]#  'a9691509-7c6b-45c3-8711-b91f560f1fe1',
#[Out]#  '09253262-5607-4fe0-8e50-3170a887ad20',
#[Out]#  'e59f4f68-17b5-4f45-a242-823e30666f34')
# Mon, 25 Jan 2021 21:33:51
get_ipython().system('pwd')
# Mon, 25 Jan 2021 21:33:56
get_ipython().system('ls')
# Mon, 25 Jan 2021 21:34:13
get_ipython().system('nanoe pyusaxs.mac')
# Mon, 25 Jan 2021 21:34:16
get_ipython().system('nano pyusaxs.mac')
# Mon, 25 Jan 2021 21:34:52
RE(run_command_file("pyusaxs.mac"))
#[Out]# ('59afb7f9-f9db-4a64-847c-9232abaf72bd',
#[Out]#  '5e247d91-fda8-41c3-a22c-7d07c8eebaf8',
#[Out]#  'be31e792-5de4-4211-8d71-0d94bd519ffc',
#[Out]#  'd77e5f74-739f-4850-9cbb-6cd0c260bb0b')
# Mon, 25 Jan 2021 21:38:29
listobjects()
#[Out]# <pyRestTable.rest_table.Table at 0x7f5767050340>
# Mon, 25 Jan 2021 21:38:46
get_ipython().system('nano pyusaxs.mac')
# Mon, 25 Jan 2021 21:39:02
get_ipython().system('nano tester.py')
# Mon, 25 Jan 2021 21:43:16
RE(run_command_file("pyusaxs.mac"))
#[Out]# ('a8584fcd-92ae-4748-9d55-e92bb95f0611',
#[Out]#  'e37518ca-d478-43e0-911d-7abe2f392b2b',
#[Out]#  'de729f53-caec-452a-a5ae-8bd1d36bdb47',
#[Out]#  '6107dcc2-ec60-472d-85f2-61399d4be8a1')
# Mon, 25 Jan 2021 21:52:17
get_ipython().system('cat pyusaxs.mac')
# Mon, 25 Jan 2021 21:52:35
get_ipython().system('cat tester.py')
# Mon, 25 Jan 2021 22:00:59
get_ipython().system('nan')
# Mon, 25 Jan 2021 22:01:08
get_ipython().system('nano tester.py')
# Mon, 25 Jan 2021 22:01:43
sd.baseline = []
# Mon, 25 Jan 2021 22:01:45
newUser("test")
#[Out]# '/share1/USAXS_data/2021-01/01_25_test'
# Mon, 25 Jan 2021 22:01:59
email_notices.addresses = ['jemian@anl.gov',]
# Mon, 25 Jan 2021 22:02:11
RE(run_command_file("pyusaxs.mac"))
#[Out]# ('dc7f83ed-35a4-4b1f-95fe-d770d853b371',
#[Out]#  '13015076-7316-4f59-a954-9180698d0eef',
#[Out]#  '7ca45d41-5a2b-45f7-acdd-a36a91782084',
#[Out]#  'bdd73f35-52d7-4f14-9124-b5e3495657b3')
# Mon, 25 Jan 2021 22:03:53
get_ipython().system('ls .logs')
# Mon, 25 Jan 2021 22:04:10
get_ipython().system('cat .logs/ipython_console.log')

```

**Comment by prjemian** [comment]
Let's look at what was recorded for the documentation run of this command file.  Need to read the data from the databroker.  Without explanations, these are the steps from the ipython command line:

```python
In [44]: import databroker

In [45]: db = databroker.catalog["mongodb_config"].v1

In [46]: run = db.v2["dc7f83e"]

In [47]: run.primary.metadata["start"]["plan_name"]
Out[47]: 'documentation_run'

In [48]: print(run.primary.to_dask().text.values[0])
Command file: pyusaxs.mac
====== ======================= ====================
line # action                  parameters          
====== ======================= ====================
3      CURRENT_EXPERIMENT_NAME enable, new, feature
4      run_python              localfile.py        
5      run                     user/localfile.py   
6      run                     tester.py           
====== ======================= ====================

```

**Comment by prjemian** [comment]
Good that we know what commands were issued but it is obvious we should also log the contents of any file loaded from the `run_python` (alias: `run`) command.  In this case, `tester.py`.

**Comment by prjemian** [comment]
Also, we will drop these TODO items (**in this PR**): https://github.com/APS-USAXS/ipython-usaxs/blob/d9cce50b622d21998407954a107cbedbaa21052e/profile_bluesky/startup/instrument/plans/command_list.py#L526-L527

Not only are they potential security holes, but this creates a nested implementation of plans that needs to be designed more carefully.

**Pull request merged**
